baseURL = 'https://gmoriki.github.io/lotustest'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

[params]

    [params.footer]
        copyright = "© :YEAR: Lotus Labs. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
        # version = true # includes git commit info

    [params.social]
        github = "gmoriki"        # YOUR_GITHUB_ID or YOUR_GITHUB_URL
        twitter = "pogohopper8"       # YOUR_TWITTER_ID
        # instagram = "colinwilson"     # YOUR_INSTAGRAM_ID
        # rss = true                    # show rss icon with link